### ISSUE TITLE
Breathing cycles before alerts come into play

### ISSUE THREAD

**Issue by tomco10** [Reznic/Inhalator#15]
We only have support for verifying first breathing cycle at the moment.
We need to add support to ignore the first X breathing cycles before starting to raise alerts.

**Comment by tomco10** [comment]
My initial thought was to support ignoring all alerts for the first X breathing cycles. Do you think this is still relevant?

**Comment by avrahamshukron** [comment]
It must not be based on first X number of breath cycles.
It should be based on time.

Consider this:
Machine starts, never finishes X breaths -> no alerts....

**Comment by tomco10** [comment]
This is also a valid concept. The main idea was to prevent alerting during installation or startup before the ventilation gets time to settle.. I still think counting breaths is more effective as it means the machine is working..

**Comment by tomco10** [comment]
Should I close this? I understand it is now part of the version...
