### ISSUE TITLE
Increase flow measurements rate

### ISSUE THREAD

**Issue by Reznic** [Reznic/Inhalator#257]
We saw that by increasing flow sampling rate, and averaging it, we get more accurate and noise free graph.
The main bottleneck for the rate is the gui update. we'll start with separating that into 2 threads, and later, 2 processes?

**Comment by osherdp** [comment]
Currently, the integration team gets good results from the current smoothing (6 samples average and regular 30Hz sampling).
We need to first make sure it's not enough
