### ISSUE TITLE
Fix combined alerts bug

### ISSUE THREAD

**Issue by Reznic** [Reznic/Inhalator#32]
currently when multiple new alerts detected in a sample, we do a bitwise-or between them. that creates error code which do not exist in the dict.
Program crashes as result

**Comment by rinslow** [comment]
Solved in one line 
in alert_bar.py:
```python
            self.set_alert(self.error_dict[last_alert_code])
```

Should be changed to:
```python
            self.set_alert(self.error_dict.get(last_alert_code, "Multiple Errors"))
```
